services:
  trivy-nginx:
    image: ghcr.io/aquasecurity/trivy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - trivy-cache:/root/.cache/trivy
      - ./reports:/reports
    command: image --format json --output /reports/nginx-1.14.json nginx:1.14

  trivy-python:
    image: ghcr.io/aquasecurity/trivy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - trivy-cache:/root/.cache/trivy
      - ./reports:/reports
    command: image --format json --output /reports/python-3.6-slim.json python:3.6-slim

volumes:
  trivy-cache:
